In [1]:
import sys
import os
from pathlib import Path
import pandas as pd
import requests
import io
from dotenv import load_dotenv
import openpyxl

load_dotenv()
DIR = Path().resolve().parent
if str(DIR) not in sys.path:
    sys.path.append(str(DIR))

from src.performance_dashboard.services.sharepoint_client import get_folder_items, get_file_content, get_sharepoint_file
from src.performance_dashboard.utils import get_secret

In [ ]:
file = "Werknemers_gegevens - Test.xlsx"
data_file = "employee_name.xlsx"
sub_folder = get_secret("COMBINED_RESPONSES_FOLDER")

In [7]:
df = get_sharepoint_file(file = data_file, sheet_name= "Opdrachtgever Reviews", sub_folder = sub_folder)
df

✅ Connected with site: Veneficus Data Safe
✅ Found Site ID: veneficus.sharepoint.com,e7754da8-bfb5-427b-bae9-2daa9d0eacbc,3b7a57d3-1d9a-4263-9719-aa56cea0efb7

📁 Content of map 'HR Cycle':
   📁 Naam: TypeformData
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/Gedeelde%20documenten/HR%20Cycle/TypeformData
   📄 Naam: Testbestan.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7B49BD27D0-9AAF-42B9-A292-5F4D741D1DFD%7D&file=Testbestan.xlsx&action=default&mobileredirect=true
   📄 Naam: Werknemers_gegevens - Test.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7BD01E5630-2F37-4476-AA36-5BFECEB80C33%7D&file=Werknemers_gegevens%20-%20Test.xlsx&action=default&mobileredirect=true
   📄 Naam: Werknemers_gegevens.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7B144D491D-5701-47A0-81E2-E75F9C99EF74%7D&file=Werknemers_gegevens.xlsx&action=default&mobileredirect=true

,Datum,Waarde & Vakmanschap,Eigenaarschap & Resultaat,Communicatie & Invloed
0,2026-01-20,1,4,0

In [2]:
sub_folder = get_secret("COMBINED_RESPONSES_FOLDER")
file = get_secret("COMBINED_DATA_DUMMY") #this has to be combined with the person_id to get the accurate file variable
df_peer = get_sharepoint_file(file = file, sheet_name= "Peer Reviews", sub_folder = sub_folder)
df_client = get_sharepoint_file(file = file, sheet_name= "Opdrachtgever Reviews", sub_folder = sub_folder)

✅ Connected with site: Veneficus Data Safe
✅ Found Site ID: veneficus.sharepoint.com,e7754da8-bfb5-427b-bae9-2daa9d0eacbc,3b7a57d3-1d9a-4263-9719-aa56cea0efb7

📁 Content of map 'HR Cycle':
   📁 Naam: TypeformData
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/Gedeelde%20documenten/HR%20Cycle/TypeformData
   📄 Naam: Testbestan.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7B49BD27D0-9AAF-42B9-A292-5F4D741D1DFD%7D&file=Testbestan.xlsx&action=default&mobileredirect=true
   📄 Naam: Werknemers_gegevens - Test.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7BD01E5630-2F37-4476-AA36-5BFECEB80C33%7D&file=Werknemers_gegevens%20-%20Test.xlsx&action=default&mobileredirect=true
   📄 Naam: Werknemers_gegevens.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7B144D491D-5701-47A0-81E2-E75F9C99EF74%7D&file=Werknemers_gegevens.xlsx&action=default&mobileredirect=true
✅ Connected with site: Veneficus Data Safe
✅ Found Site ID: veneficus.sharepoint.com,e7754da8-bfb5-427b-bae9-2daa9d0eacbc,3b7a57d3-1d9a-4263-9719-aa56cea0efb7

📁 Content of map 'HR Cycle':
   📁 Naam: TypeformData
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/Gedeelde%20documenten/HR%20Cycle/TypeformData
   📄 Naam: Testbestan.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7B49BD27D0-9AAF-42B9-A292-5F4D741D1DFD%7D&file=Testbestan.xlsx&action=default&mobileredirect=true
   📄 Naam: Werknemers_gegevens - Test.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7BD01E5630-2F37-4476-AA36-5BFECEB80C33%7D&file=Werknemers_gegevens%20-%20Test.xlsx&action=default&mobileredirect=true
   📄 Naam: Werknemers_gegevens.xlsx
      URL: https://veneficus.sharepoint.com/sites/VeneficusDataSafe/_layouts/15/Doc.aspx?sourcedoc=%7B144D491D-5701-47A0-81E2-E75F9C99EF74%7D&file=Werknemers_gegevens.xlsx&action=default&mobileredirect=true

In [ ]:
df_peer

,Datum,Analyse & Probleemoplossing,Kwaliteit & Vakmanschap,Visualisatie & Verhaal,Business & Context,Samenwerken & Communicatie,Eigenaarschap & Initiatief
0,2026-01-20,1,1,2,1,2,2

In [11]:
df_peer.Datum.iloc[-1].date()

datetime.date(2026, 1, 20)